//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumourMill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leader
    {
        public int LeaderId { get; set; }
        public string LeaderName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    }
}
